image: gitlab_runner_images:12.13.0-alpine
deploy develop:
  stage: deploy
  before_script:
    - rm -rf ~/.ssh || true
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no -T "arrow@192.168.1.4"
    - scp -i ~/.ssh/id_rsa -o 'StrictHostKeyChecking no' -r ./* arrow@192.168.1.4:/home/arrow/projects/jira_qcd_test/jira_qcd_api/
    - ssh -T arrow@192.168.1.4 "cd /home/arrow/projects/jira_qcd_test/jira_qcd_api/; yarn install; yarn knex-it; pm2 restart jira_qcd_test"
  only:
    - develop

deploy master:
  stage: deploy
  before_script:
    - rm -rf ~/.ssh || true
    - mkdir ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
  script:
    - ssh -o StrictHostKeyChecking=no -T "arrow@192.168.1.4"
    - scp -i ~/.ssh/id_rsa -o 'StrictHostKeyChecking no' -r ./* arrow@192.168.1.4:/home/arrow/projects/jira_qcd/jira_qcd/
    - ssh -T arrow@192.168.1.4 "cd /home/arrow/projects/jira_qcd/jira_qcd/; yarn install; yarn knex-prod; pm2 restart jira_qcd"
  only:
    - master
