CREATE TABLE project_role_cost (
	id serial PRIMARY KEY,
	name VARCHAR (255) UNIQUE NOT NULL,
	delete_flg BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);